sudo: false
language: rust
rust: nightly

addons:
  apt:
    packages: libxml2-dev

after_success: ./scripts/doc-upload.sh
env:
  global:
    secure: "lYfydO4axg/baSnNhXqiyz/2Rd0ixQVVThGXt65lzB72t+XKZFtViX1KNrk2v3oVUxuwOlraE5rn3wT/cB3UiwwbmYGNlqMWB64URSJwegeviiB3ofD8iCfLmNctgbiDGrglSpubTJuu2GVF1NU5FHzTsy4MuPrURqJ3PWdnoU9ZLynQN+WyvTPMHq5nyv3l6mlNXRqY8ylgu1bWZwODkJCA2a7dWnAXyvU8J75PuUPpNc9ArhxsJQgX8Aur9OYgfjMItPSb4ovqEdLOkMLAGvinCdWcbSaqEMM8AncANlrz61mbhKKtW0OIPxNSMfcQRlAW6ulYYiK+GgORpiaWNbSRgZzj0XotWOj14KY56yTkC84QQgwlSGfPqY7xFhIQehUNkep9/elNu8gJjUBeS2yj1QgVs64NQiG+/pfJTKwd8toWcnMzsxZTv1dziTUcZZMlbmQFXfIMjZQfM2dAIJNDUeSDZNCyoML6mZxJ2Wdq/1CdUz46RlawIYs2SjQqdNL6rEMQFOBp0goUsVzzejJvNcZXoLYbv8F0FBHglKKTEsXPz7dqmieS84ytsCxIw/UZspYiCGulXd+S0odNzJklG8F+QjdEQA1rMlCFOgTYzocNw6IwMdxofgfINlDvGo1LnEhVAivBKMb52OEIGh2crr+CnBSHkegAFC/VnBY="
