[package]
name = "llamapun"
version = "0.0.1"
authors = ["Deyan Ginev <deyan.ginev@gmail.com>","Jan Frederik Schaefer <j.schaefer@jacobs-university.de>"]

[lib]
name = "llamapun"
crate-type = ["rlib", "dylib", "staticlib"]

[dependencies.rustmorpha]
git = "https://github.com/jfschaefer/rust-morpha.git"
[dependencies.rust-senna]
git = "https://github.com/jfschaefer/rust-senna.git"
version = "*"

[dependencies]
libc = "0.1"
regex = "0.1"
time = "0.1"
walkdir = "0.1"
libxml = "0.0.7481"
gnuplot = "0.0.21"
unidecode = "0.2"
rust-crypto = "0.2"
lazy_static = "0.1"
